name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"
      with:
        submodules: true

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 11

    - name: "Restore Cache"
      uses: "actions/cache@v4"
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}"
        restore-keys: "${{ runner.os }}-deps-"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 1.10.3.1040
        bb: latest

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: npx on Windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        where npx
        bb -e '(babashka.process/shell "npx")'
        bb -e '(babashka.process/shell "npx -v")'

    - name: Run tests
      shell: bash
      run: |
        npx -v
        npm install
        bb test:node
        bb test:bb
        bb test:clj

    - name: Run library tests
      if: matrix.os != 'windows-latest'
      run: |
        npm install --global yarn
        bb test:libs
